# Generated by Django 4.1.3 on 2022-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_animal', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=4)),
            ],
        ),
    ]
