# Generated by Django 4.1.3 on 2022-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='age',
            field=models.IntegerField(),
        ),
    ]
