# Generated by Django 4.1.3 on 2022-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_alter_animalprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='sex_of_animal',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
