# Generated by Django 4.1.3 on 2022-11-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_animalprofile_sex_of_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='sex_of_animal',
            field=models.CharField(default='female', max_length=20),
        ),
    ]
